// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: clientmessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ClientMessage_Greet_
	//	*ClientMessage_GreetWithId_
	//	*ClientMessage_SendPublicKey
	Variant isClientMessage_Variant `protobuf_oneof:"variant"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clientmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_clientmessage_proto_rawDescGZIP(), []int{0}
}

func (m *ClientMessage) GetVariant() isClientMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ClientMessage) GetGreet() *ClientMessage_Greet {
	if x, ok := x.GetVariant().(*ClientMessage_Greet_); ok {
		return x.Greet
	}
	return nil
}

func (x *ClientMessage) GetGreetWithId() *ClientMessage_GreetWithId {
	if x, ok := x.GetVariant().(*ClientMessage_GreetWithId_); ok {
		return x.GreetWithId
	}
	return nil
}

func (x *ClientMessage) GetSendPublicKey() *ClientMessageSendPublicKey {
	if x, ok := x.GetVariant().(*ClientMessage_SendPublicKey); ok {
		return x.SendPublicKey
	}
	return nil
}

type isClientMessage_Variant interface {
	isClientMessage_Variant()
}

type ClientMessage_Greet_ struct {
	Greet *ClientMessage_Greet `protobuf:"bytes,1,opt,name=greet,proto3,oneof"`
}

type ClientMessage_GreetWithId_ struct {
	GreetWithId *ClientMessage_GreetWithId `protobuf:"bytes,2,opt,name=greet_with_id,json=greetWithId,proto3,oneof"`
}

type ClientMessage_SendPublicKey struct {
	SendPublicKey *ClientMessageSendPublicKey `protobuf:"bytes,3,opt,name=send_public_key,json=sendPublicKey,proto3,oneof"`
}

func (*ClientMessage_Greet_) isClientMessage_Variant() {}

func (*ClientMessage_GreetWithId_) isClientMessage_Variant() {}

func (*ClientMessage_SendPublicKey) isClientMessage_Variant() {}

type ClientMessage_Greet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ClientMessage_Greet) Reset() {
	*x = ClientMessage_Greet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_Greet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_Greet) ProtoMessage() {}

func (x *ClientMessage_Greet) ProtoReflect() protoreflect.Message {
	mi := &file_clientmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_Greet.ProtoReflect.Descriptor instead.
func (*ClientMessage_Greet) Descriptor() ([]byte, []int) {
	return file_clientmessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClientMessage_Greet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ClientMessage_GreetWithId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ClientMessage_GreetWithId) Reset() {
	*x = ClientMessage_GreetWithId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_GreetWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_GreetWithId) ProtoMessage() {}

func (x *ClientMessage_GreetWithId) ProtoReflect() protoreflect.Message {
	mi := &file_clientmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_GreetWithId.ProtoReflect.Descriptor instead.
func (*ClientMessage_GreetWithId) Descriptor() ([]byte, []int) {
	return file_clientmessage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClientMessage_GreetWithId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientMessage_GreetWithId) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ClientMessageSendPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPem string `protobuf:"bytes,1,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
}

func (x *ClientMessageSendPublicKey) Reset() {
	*x = ClientMessageSendPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientmessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessageSendPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessageSendPublicKey) ProtoMessage() {}

func (x *ClientMessageSendPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_clientmessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessageSendPublicKey.ProtoReflect.Descriptor instead.
func (*ClientMessageSendPublicKey) Descriptor() ([]byte, []int) {
	return file_clientmessage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClientMessageSendPublicKey) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

var File_clientmessage_proto protoreflect.FileDescriptor

var file_clientmessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xe7, 0x02, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a,
	0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x48, 0x00, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x12, 0x45, 0x0a, 0x0d, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x1a, 0x21, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x37, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x1a, 0x28, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x50, 0x65, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientmessage_proto_rawDescOnce sync.Once
	file_clientmessage_proto_rawDescData = file_clientmessage_proto_rawDesc
)

func file_clientmessage_proto_rawDescGZIP() []byte {
	file_clientmessage_proto_rawDescOnce.Do(func() {
		file_clientmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientmessage_proto_rawDescData)
	})
	return file_clientmessage_proto_rawDescData
}

var file_clientmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clientmessage_proto_goTypes = []interface{}{
	(*ClientMessage)(nil),              // 0: main.ClientMessage
	(*ClientMessage_Greet)(nil),        // 1: main.ClientMessage.Greet
	(*ClientMessage_GreetWithId)(nil),  // 2: main.ClientMessage.GreetWithId
	(*ClientMessageSendPublicKey)(nil), // 3: main.ClientMessage.sendPublicKey
}
var file_clientmessage_proto_depIdxs = []int32{
	1, // 0: main.ClientMessage.greet:type_name -> main.ClientMessage.Greet
	2, // 1: main.ClientMessage.greet_with_id:type_name -> main.ClientMessage.GreetWithId
	3, // 2: main.ClientMessage.send_public_key:type_name -> main.ClientMessage.sendPublicKey
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clientmessage_proto_init() }
func file_clientmessage_proto_init() {
	if File_clientmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientmessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_Greet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientmessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_GreetWithId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientmessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessageSendPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_clientmessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMessage_Greet_)(nil),
		(*ClientMessage_GreetWithId_)(nil),
		(*ClientMessage_SendPublicKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientmessage_proto_goTypes,
		DependencyIndexes: file_clientmessage_proto_depIdxs,
		MessageInfos:      file_clientmessage_proto_msgTypes,
	}.Build()
	File_clientmessage_proto = out.File
	file_clientmessage_proto_rawDesc = nil
	file_clientmessage_proto_goTypes = nil
	file_clientmessage_proto_depIdxs = nil
}
