// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/clientmessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ClientMessage_SendPublicKey_
	//	*ClientMessage_LogIn_
	//	*ClientMessage_AccountRegistration_
	Variant isClientMessage_Variant `protobuf_oneof:"variant"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_clientmessage_proto_rawDescGZIP(), []int{0}
}

func (m *ClientMessage) GetVariant() isClientMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ClientMessage) GetSendPublicKey() *ClientMessage_SendPublicKey {
	if x, ok := x.GetVariant().(*ClientMessage_SendPublicKey_); ok {
		return x.SendPublicKey
	}
	return nil
}

func (x *ClientMessage) GetLogIn() *ClientMessage_LogIn {
	if x, ok := x.GetVariant().(*ClientMessage_LogIn_); ok {
		return x.LogIn
	}
	return nil
}

func (x *ClientMessage) GetAccountRegistration() *ClientMessage_AccountRegistration {
	if x, ok := x.GetVariant().(*ClientMessage_AccountRegistration_); ok {
		return x.AccountRegistration
	}
	return nil
}

type isClientMessage_Variant interface {
	isClientMessage_Variant()
}

type ClientMessage_SendPublicKey_ struct {
	SendPublicKey *ClientMessage_SendPublicKey `protobuf:"bytes,1,opt,name=send_public_key,json=sendPublicKey,proto3,oneof"`
}

type ClientMessage_LogIn_ struct {
	LogIn *ClientMessage_LogIn `protobuf:"bytes,2,opt,name=log_in,json=logIn,proto3,oneof"`
}

type ClientMessage_AccountRegistration_ struct {
	AccountRegistration *ClientMessage_AccountRegistration `protobuf:"bytes,3,opt,name=account_registration,json=accountRegistration,proto3,oneof"`
}

func (*ClientMessage_SendPublicKey_) isClientMessage_Variant() {}

func (*ClientMessage_LogIn_) isClientMessage_Variant() {}

func (*ClientMessage_AccountRegistration_) isClientMessage_Variant() {}

type ClientMessage_SendPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPem string `protobuf:"bytes,1,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
}

func (x *ClientMessage_SendPublicKey) Reset() {
	*x = ClientMessage_SendPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_SendPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_SendPublicKey) ProtoMessage() {}

func (x *ClientMessage_SendPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_SendPublicKey.ProtoReflect.Descriptor instead.
func (*ClientMessage_SendPublicKey) Descriptor() ([]byte, []int) {
	return file_proto_clientmessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClientMessage_SendPublicKey) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

type ClientMessage_LogIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientMessage_LogIn) Reset() {
	*x = ClientMessage_LogIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_LogIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_LogIn) ProtoMessage() {}

func (x *ClientMessage_LogIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_LogIn.ProtoReflect.Descriptor instead.
func (*ClientMessage_LogIn) Descriptor() ([]byte, []int) {
	return file_proto_clientmessage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClientMessage_LogIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientMessage_LogIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ClientMessage_AccountRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientMessage_AccountRegistration) Reset() {
	*x = ClientMessage_AccountRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_clientmessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_AccountRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_AccountRegistration) ProtoMessage() {}

func (x *ClientMessage_AccountRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientmessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_AccountRegistration.ProtoReflect.Descriptor instead.
func (*ClientMessage_AccountRegistration) Descriptor() ([]byte, []int) {
	return file_proto_clientmessage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClientMessage_AccountRegistration) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientMessage_AccountRegistration) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientMessage_AccountRegistration) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_clientmessage_proto protoreflect.FileDescriptor

var file_proto_clientmessage_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0xc3, 0x03, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48,
	0x00, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x32, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x49, 0x6e, 0x12, 0x5c, 0x0a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x13, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x28, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x50, 0x65, 0x6d, 0x1a, 0x39, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x63, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x09, 0x0a, 0x07,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_clientmessage_proto_rawDescOnce sync.Once
	file_proto_clientmessage_proto_rawDescData = file_proto_clientmessage_proto_rawDesc
)

func file_proto_clientmessage_proto_rawDescGZIP() []byte {
	file_proto_clientmessage_proto_rawDescOnce.Do(func() {
		file_proto_clientmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_clientmessage_proto_rawDescData)
	})
	return file_proto_clientmessage_proto_rawDescData
}

var file_proto_clientmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_clientmessage_proto_goTypes = []interface{}{
	(*ClientMessage)(nil),                     // 0: main.ClientMessage
	(*ClientMessage_SendPublicKey)(nil),       // 1: main.ClientMessage.SendPublicKey
	(*ClientMessage_LogIn)(nil),               // 2: main.ClientMessage.LogIn
	(*ClientMessage_AccountRegistration)(nil), // 3: main.ClientMessage.AccountRegistration
}
var file_proto_clientmessage_proto_depIdxs = []int32{
	1, // 0: main.ClientMessage.send_public_key:type_name -> main.ClientMessage.SendPublicKey
	2, // 1: main.ClientMessage.log_in:type_name -> main.ClientMessage.LogIn
	3, // 2: main.ClientMessage.account_registration:type_name -> main.ClientMessage.AccountRegistration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_clientmessage_proto_init() }
func file_proto_clientmessage_proto_init() {
	if File_proto_clientmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_clientmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clientmessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_SendPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clientmessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_LogIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_clientmessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_AccountRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_clientmessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMessage_SendPublicKey_)(nil),
		(*ClientMessage_LogIn_)(nil),
		(*ClientMessage_AccountRegistration_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_clientmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_clientmessage_proto_goTypes,
		DependencyIndexes: file_proto_clientmessage_proto_depIdxs,
		MessageInfos:      file_proto_clientmessage_proto_msgTypes,
	}.Build()
	File_proto_clientmessage_proto = out.File
	file_proto_clientmessage_proto_rawDesc = nil
	file_proto_clientmessage_proto_goTypes = nil
	file_proto_clientmessage_proto_depIdxs = nil
}
