// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.1
// source: proto/servermessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ServerMessage_ConfirmKeyExchange_
	//	*ServerMessage_ConfirmLogIn_
	//	*ServerMessage_AccountRegistrationResult_
	//	*ServerMessage_AccountRegistrationCodeResult_
	//	*ServerMessage_SendUserList_
	//	*ServerMessage_SendPublicKey_
	//	*ServerMessage_SendChatList_
	Variant isServerMessage_Variant `protobuf_oneof:"variant"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0}
}

func (m *ServerMessage) GetVariant() isServerMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ServerMessage) GetConfirmKeyExchange() *ServerMessage_ConfirmKeyExchange {
	if x, ok := x.GetVariant().(*ServerMessage_ConfirmKeyExchange_); ok {
		return x.ConfirmKeyExchange
	}
	return nil
}

func (x *ServerMessage) GetConfirmLogIn() *ServerMessage_ConfirmLogIn {
	if x, ok := x.GetVariant().(*ServerMessage_ConfirmLogIn_); ok {
		return x.ConfirmLogIn
	}
	return nil
}

func (x *ServerMessage) GetAccountRegistrationResult() *ServerMessage_AccountRegistrationResult {
	if x, ok := x.GetVariant().(*ServerMessage_AccountRegistrationResult_); ok {
		return x.AccountRegistrationResult
	}
	return nil
}

func (x *ServerMessage) GetAccountRegistrationCodeResult() *ServerMessage_AccountRegistrationCodeResult {
	if x, ok := x.GetVariant().(*ServerMessage_AccountRegistrationCodeResult_); ok {
		return x.AccountRegistrationCodeResult
	}
	return nil
}

func (x *ServerMessage) GetSendUserList() *ServerMessage_SendUserList {
	if x, ok := x.GetVariant().(*ServerMessage_SendUserList_); ok {
		return x.SendUserList
	}
	return nil
}

func (x *ServerMessage) GetSendPublicKey() *ServerMessage_SendPublicKey {
	if x, ok := x.GetVariant().(*ServerMessage_SendPublicKey_); ok {
		return x.SendPublicKey
	}
	return nil
}

func (x *ServerMessage) GetSendChatList() *ServerMessage_SendChatList {
	if x, ok := x.GetVariant().(*ServerMessage_SendChatList_); ok {
		return x.SendChatList
	}
	return nil
}

type isServerMessage_Variant interface {
	isServerMessage_Variant()
}

type ServerMessage_ConfirmKeyExchange_ struct {
	ConfirmKeyExchange *ServerMessage_ConfirmKeyExchange `protobuf:"bytes,1,opt,name=confirm_key_exchange,json=confirmKeyExchange,proto3,oneof"`
}

type ServerMessage_ConfirmLogIn_ struct {
	ConfirmLogIn *ServerMessage_ConfirmLogIn `protobuf:"bytes,2,opt,name=confirm_log_in,json=confirmLogIn,proto3,oneof"`
}

type ServerMessage_AccountRegistrationResult_ struct {
	AccountRegistrationResult *ServerMessage_AccountRegistrationResult `protobuf:"bytes,3,opt,name=account_registration_result,json=accountRegistrationResult,proto3,oneof"`
}

type ServerMessage_AccountRegistrationCodeResult_ struct {
	AccountRegistrationCodeResult *ServerMessage_AccountRegistrationCodeResult `protobuf:"bytes,4,opt,name=account_registration_code_result,json=accountRegistrationCodeResult,proto3,oneof"`
}

type ServerMessage_SendUserList_ struct {
	SendUserList *ServerMessage_SendUserList `protobuf:"bytes,5,opt,name=send_user_list,json=sendUserList,proto3,oneof"`
}

type ServerMessage_SendPublicKey_ struct {
	SendPublicKey *ServerMessage_SendPublicKey `protobuf:"bytes,6,opt,name=send_public_key,json=sendPublicKey,proto3,oneof"`
}

type ServerMessage_SendChatList_ struct {
	SendChatList *ServerMessage_SendChatList `protobuf:"bytes,7,opt,name=send_chat_list,json=sendChatList,proto3,oneof"`
}

func (*ServerMessage_ConfirmKeyExchange_) isServerMessage_Variant() {}

func (*ServerMessage_ConfirmLogIn_) isServerMessage_Variant() {}

func (*ServerMessage_AccountRegistrationResult_) isServerMessage_Variant() {}

func (*ServerMessage_AccountRegistrationCodeResult_) isServerMessage_Variant() {}

func (*ServerMessage_SendUserList_) isServerMessage_Variant() {}

func (*ServerMessage_SendPublicKey_) isServerMessage_Variant() {}

func (*ServerMessage_SendChatList_) isServerMessage_Variant() {}

type ServerMessage_ConfirmKeyExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerMessage_ConfirmKeyExchange) Reset() {
	*x = ServerMessage_ConfirmKeyExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_ConfirmKeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_ConfirmKeyExchange) ProtoMessage() {}

func (x *ServerMessage_ConfirmKeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_ConfirmKeyExchange.ProtoReflect.Descriptor instead.
func (*ServerMessage_ConfirmKeyExchange) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 0}
}

type ServerMessage_ConfirmLogIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool  `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Id         int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerMessage_ConfirmLogIn) Reset() {
	*x = ServerMessage_ConfirmLogIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_ConfirmLogIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_ConfirmLogIn) ProtoMessage() {}

func (x *ServerMessage_ConfirmLogIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_ConfirmLogIn.ProtoReflect.Descriptor instead.
func (*ServerMessage_ConfirmLogIn) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServerMessage_ConfirmLogIn) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ServerMessage_ConfirmLogIn) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServerMessage_AccountRegistrationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful    bool    `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	EmailError    *string `protobuf:"bytes,2,opt,name=email_error,json=emailError,proto3,oneof" json:"email_error,omitempty"`
	UsernameError *string `protobuf:"bytes,3,opt,name=username_error,json=usernameError,proto3,oneof" json:"username_error,omitempty"`
	PasswordError *string `protobuf:"bytes,4,opt,name=password_error,json=passwordError,proto3,oneof" json:"password_error,omitempty"`
}

func (x *ServerMessage_AccountRegistrationResult) Reset() {
	*x = ServerMessage_AccountRegistrationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_AccountRegistrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_AccountRegistrationResult) ProtoMessage() {}

func (x *ServerMessage_AccountRegistrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_AccountRegistrationResult.ProtoReflect.Descriptor instead.
func (*ServerMessage_AccountRegistrationResult) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ServerMessage_AccountRegistrationResult) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ServerMessage_AccountRegistrationResult) GetEmailError() string {
	if x != nil && x.EmailError != nil {
		return *x.EmailError
	}
	return ""
}

func (x *ServerMessage_AccountRegistrationResult) GetUsernameError() string {
	if x != nil && x.UsernameError != nil {
		return *x.UsernameError
	}
	return ""
}

func (x *ServerMessage_AccountRegistrationResult) GetPasswordError() string {
	if x != nil && x.PasswordError != nil {
		return *x.PasswordError
	}
	return ""
}

type ServerMessage_AccountRegistrationCodeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful    bool    `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	CriticalError bool    `protobuf:"varint,2,opt,name=criticalError,proto3" json:"criticalError,omitempty"`
	Error         *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *ServerMessage_AccountRegistrationCodeResult) Reset() {
	*x = ServerMessage_AccountRegistrationCodeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_AccountRegistrationCodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_AccountRegistrationCodeResult) ProtoMessage() {}

func (x *ServerMessage_AccountRegistrationCodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_AccountRegistrationCodeResult.ProtoReflect.Descriptor instead.
func (*ServerMessage_AccountRegistrationCodeResult) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ServerMessage_AccountRegistrationCodeResult) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ServerMessage_AccountRegistrationCodeResult) GetCriticalError() bool {
	if x != nil {
		return x.CriticalError
	}
	return false
}

func (x *ServerMessage_AccountRegistrationCodeResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ServerMessage_SendUserList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*ServerMessage_SendUserList_User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ServerMessage_SendUserList) Reset() {
	*x = ServerMessage_SendUserList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_SendUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_SendUserList) ProtoMessage() {}

func (x *ServerMessage_SendUserList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_SendUserList.ProtoReflect.Descriptor instead.
func (*ServerMessage_SendUserList) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ServerMessage_SendUserList) GetUsers() []*ServerMessage_SendUserList_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ServerMessage_SendPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ServerMessage_SendPublicKey) Reset() {
	*x = ServerMessage_SendPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_SendPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_SendPublicKey) ProtoMessage() {}

func (x *ServerMessage_SendPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_SendPublicKey.ProtoReflect.Descriptor instead.
func (*ServerMessage_SendPublicKey) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ServerMessage_SendPublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ServerMessage_SendChatList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chats []*ServerMessage_SendChatList_Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
}

func (x *ServerMessage_SendChatList) Reset() {
	*x = ServerMessage_SendChatList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_SendChatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_SendChatList) ProtoMessage() {}

func (x *ServerMessage_SendChatList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_SendChatList.ProtoReflect.Descriptor instead.
func (*ServerMessage_SendChatList) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ServerMessage_SendChatList) GetChats() []*ServerMessage_SendChatList_Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ServerMessage_SendUserList_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id       uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerMessage_SendUserList_User) Reset() {
	*x = ServerMessage_SendUserList_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_SendUserList_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_SendUserList_User) ProtoMessage() {}

func (x *ServerMessage_SendUserList_User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_SendUserList_User.ProtoReflect.Descriptor instead.
func (*ServerMessage_SendUserList_User) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *ServerMessage_SendUserList_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerMessage_SendUserList_User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServerMessage_SendChatList_Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientUsername string `protobuf:"bytes,2,opt,name=recipient_username,json=recipientUsername,proto3" json:"recipient_username,omitempty"`
	RecipientId       uint32 `protobuf:"varint,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
}

func (x *ServerMessage_SendChatList_Chat) Reset() {
	*x = ServerMessage_SendChatList_Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_SendChatList_Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_SendChatList_Chat) ProtoMessage() {}

func (x *ServerMessage_SendChatList_Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_SendChatList_Chat.ProtoReflect.Descriptor instead.
func (*ServerMessage_SendChatList_Chat) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *ServerMessage_SendChatList_Chat) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerMessage_SendChatList_Chat) GetRecipientUsername() string {
	if x != nil {
		return x.RecipientUsername
	}
	return ""
}

func (x *ServerMessage_SendChatList_Chat) GetRecipientId() uint32 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

var File_proto_servermessage_proto protoreflect.FileDescriptor

var file_proto_servermessage_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0xce, 0x0b, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x5a, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65,
	0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x48, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x12, 0x6f, 0x0a, 0x1b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52,
	0x19, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x7c, 0x0a, 0x20, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x1d, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x4b, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48, 0x00,
	0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x48, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x6e,
	0x64, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x1a,
	0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0xef, 0x01, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x12, 0x24, 0x0a,
	0x0b, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x2a, 0x0a, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0d, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x11,
	0x0a, 0x0f, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x1a, 0x8a, 0x01, 0x0a, 0x1d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x72, 0x69, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x7f,
	0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x32, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0x2e, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x1a,
	0xb5, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x1a, 0x68, 0x0a,
	0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_servermessage_proto_rawDescOnce sync.Once
	file_proto_servermessage_proto_rawDescData = file_proto_servermessage_proto_rawDesc
)

func file_proto_servermessage_proto_rawDescGZIP() []byte {
	file_proto_servermessage_proto_rawDescOnce.Do(func() {
		file_proto_servermessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_servermessage_proto_rawDescData)
	})
	return file_proto_servermessage_proto_rawDescData
}

var file_proto_servermessage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_servermessage_proto_goTypes = []interface{}{
	(*ServerMessage)(nil),                               // 0: main.ServerMessage
	(*ServerMessage_ConfirmKeyExchange)(nil),            // 1: main.ServerMessage.ConfirmKeyExchange
	(*ServerMessage_ConfirmLogIn)(nil),                  // 2: main.ServerMessage.ConfirmLogIn
	(*ServerMessage_AccountRegistrationResult)(nil),     // 3: main.ServerMessage.AccountRegistrationResult
	(*ServerMessage_AccountRegistrationCodeResult)(nil), // 4: main.ServerMessage.AccountRegistrationCodeResult
	(*ServerMessage_SendUserList)(nil),                  // 5: main.ServerMessage.SendUserList
	(*ServerMessage_SendPublicKey)(nil),                 // 6: main.ServerMessage.SendPublicKey
	(*ServerMessage_SendChatList)(nil),                  // 7: main.ServerMessage.SendChatList
	(*ServerMessage_SendUserList_User)(nil),             // 8: main.ServerMessage.SendUserList.User
	(*ServerMessage_SendChatList_Chat)(nil),             // 9: main.ServerMessage.SendChatList.Chat
}
var file_proto_servermessage_proto_depIdxs = []int32{
	1, // 0: main.ServerMessage.confirm_key_exchange:type_name -> main.ServerMessage.ConfirmKeyExchange
	2, // 1: main.ServerMessage.confirm_log_in:type_name -> main.ServerMessage.ConfirmLogIn
	3, // 2: main.ServerMessage.account_registration_result:type_name -> main.ServerMessage.AccountRegistrationResult
	4, // 3: main.ServerMessage.account_registration_code_result:type_name -> main.ServerMessage.AccountRegistrationCodeResult
	5, // 4: main.ServerMessage.send_user_list:type_name -> main.ServerMessage.SendUserList
	6, // 5: main.ServerMessage.send_public_key:type_name -> main.ServerMessage.SendPublicKey
	7, // 6: main.ServerMessage.send_chat_list:type_name -> main.ServerMessage.SendChatList
	8, // 7: main.ServerMessage.SendUserList.users:type_name -> main.ServerMessage.SendUserList.User
	9, // 8: main.ServerMessage.SendChatList.chats:type_name -> main.ServerMessage.SendChatList.Chat
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_servermessage_proto_init() }
func file_proto_servermessage_proto_init() {
	if File_proto_servermessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_servermessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_ConfirmKeyExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_ConfirmLogIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_AccountRegistrationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_AccountRegistrationCodeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_SendUserList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_SendPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_SendChatList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_SendUserList_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_SendChatList_Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_servermessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ServerMessage_ConfirmKeyExchange_)(nil),
		(*ServerMessage_ConfirmLogIn_)(nil),
		(*ServerMessage_AccountRegistrationResult_)(nil),
		(*ServerMessage_AccountRegistrationCodeResult_)(nil),
		(*ServerMessage_SendUserList_)(nil),
		(*ServerMessage_SendPublicKey_)(nil),
		(*ServerMessage_SendChatList_)(nil),
	}
	file_proto_servermessage_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_servermessage_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_servermessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_servermessage_proto_goTypes,
		DependencyIndexes: file_proto_servermessage_proto_depIdxs,
		MessageInfos:      file_proto_servermessage_proto_msgTypes,
	}.Build()
	File_proto_servermessage_proto = out.File
	file_proto_servermessage_proto_rawDesc = nil
	file_proto_servermessage_proto_goTypes = nil
	file_proto_servermessage_proto_depIdxs = nil
}
