// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/servermessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ServerMessage_ConfirmKeyExchange_
	//	*ServerMessage_Dummy_
	Variant isServerMessage_Variant `protobuf_oneof:"variant"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0}
}

func (m *ServerMessage) GetVariant() isServerMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ServerMessage) GetConfirmKeyExchange() *ServerMessage_ConfirmKeyExchange {
	if x, ok := x.GetVariant().(*ServerMessage_ConfirmKeyExchange_); ok {
		return x.ConfirmKeyExchange
	}
	return nil
}

func (x *ServerMessage) GetDummy() *ServerMessage_Dummy {
	if x, ok := x.GetVariant().(*ServerMessage_Dummy_); ok {
		return x.Dummy
	}
	return nil
}

type isServerMessage_Variant interface {
	isServerMessage_Variant()
}

type ServerMessage_ConfirmKeyExchange_ struct {
	ConfirmKeyExchange *ServerMessage_ConfirmKeyExchange `protobuf:"bytes,1,opt,name=confirm_key_exchange,json=confirmKeyExchange,proto3,oneof"`
}

type ServerMessage_Dummy_ struct {
	Dummy *ServerMessage_Dummy `protobuf:"bytes,2,opt,name=dummy,proto3,oneof"`
}

func (*ServerMessage_ConfirmKeyExchange_) isServerMessage_Variant() {}

func (*ServerMessage_Dummy_) isServerMessage_Variant() {}

type ServerMessage_ConfirmKeyExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerMessage_ConfirmKeyExchange) Reset() {
	*x = ServerMessage_ConfirmKeyExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_ConfirmKeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_ConfirmKeyExchange) ProtoMessage() {}

func (x *ServerMessage_ConfirmKeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_ConfirmKeyExchange.ProtoReflect.Descriptor instead.
func (*ServerMessage_ConfirmKeyExchange) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 0}
}

type ServerMessage_Dummy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerMessage_Dummy) Reset() {
	*x = ServerMessage_Dummy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_servermessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_Dummy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_Dummy) ProtoMessage() {}

func (x *ServerMessage_Dummy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servermessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_Dummy.ProtoReflect.Descriptor instead.
func (*ServerMessage_Dummy) Descriptor() ([]byte, []int) {
	return file_proto_servermessage_proto_rawDescGZIP(), []int{0, 1}
}

var File_proto_servermessage_proto protoreflect.FileDescriptor

var file_proto_servermessage_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0xc8, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x5a, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65,
	0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x31, 0x0a, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x48, 0x00, 0x52, 0x05, 0x64, 0x75, 0x6d,
	0x6d, 0x79, 0x1a, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4b, 0x65, 0x79,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_servermessage_proto_rawDescOnce sync.Once
	file_proto_servermessage_proto_rawDescData = file_proto_servermessage_proto_rawDesc
)

func file_proto_servermessage_proto_rawDescGZIP() []byte {
	file_proto_servermessage_proto_rawDescOnce.Do(func() {
		file_proto_servermessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_servermessage_proto_rawDescData)
	})
	return file_proto_servermessage_proto_rawDescData
}

var file_proto_servermessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_servermessage_proto_goTypes = []interface{}{
	(*ServerMessage)(nil),                    // 0: main.ServerMessage
	(*ServerMessage_ConfirmKeyExchange)(nil), // 1: main.ServerMessage.ConfirmKeyExchange
	(*ServerMessage_Dummy)(nil),              // 2: main.ServerMessage.Dummy
}
var file_proto_servermessage_proto_depIdxs = []int32{
	1, // 0: main.ServerMessage.confirm_key_exchange:type_name -> main.ServerMessage.ConfirmKeyExchange
	2, // 1: main.ServerMessage.dummy:type_name -> main.ServerMessage.Dummy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_servermessage_proto_init() }
func file_proto_servermessage_proto_init() {
	if File_proto_servermessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_servermessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_ConfirmKeyExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_servermessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_Dummy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_servermessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ServerMessage_ConfirmKeyExchange_)(nil),
		(*ServerMessage_Dummy_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_servermessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_servermessage_proto_goTypes,
		DependencyIndexes: file_proto_servermessage_proto_depIdxs,
		MessageInfos:      file_proto_servermessage_proto_msgTypes,
	}.Build()
	File_proto_servermessage_proto = out.File
	file_proto_servermessage_proto_rawDesc = nil
	file_proto_servermessage_proto_goTypes = nil
	file_proto_servermessage_proto_depIdxs = nil
}
